name: Build APK

# Lancer le workflow à chaque push sur la branche main
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    # Le serveur Ubuntu utilisé par GitHub Actions
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Récupérer le code du repo
    - name: Checkout repo
      uses: actions/checkout@v3

    # 2️⃣ Installer Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3️⃣ Installer les dépendances Linux + Python + Buildozer
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-setuptools git python3-dev \
        build-essential autoconf libtool pkg-config zlib1g-dev \
        libncurses5-dev libffi-dev libssl-dev

        pip install --upgrade pip
        pip install buildozer cython kivy

    # 4️⃣ Compiler l'application en APK
    - name: Build APK
      run: |
        buildozer android debug

    # 5️⃣ Upload de l'APK généré pour le récupérer
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: MonApp-APK
        path: bin/*.apk
